project:
  type: book # website
  output-dir: "_build"
  preview:
    port: 4567
    browser: true

# https://quarto.org/docs/books/
# https://quarto.org/docs/reference/projects/books.html
book:
  title: "Quality Control for Python Applications"
  author: "Michael Rossetti"
  date: "last-modified" # "7/24/2024"
  date-format: "iso"
  #doi: "...."
  #isbn: "..."
  #issn: "..."
  #edition: "v2"

#website:

  site-url: https://s2t2.github.io/quality-control-workshop-2024
  repo-url: https://github.com/s2t2/quality-control-workshop-2024
  repo-branch: main
  repo-subdir: docs
  repo-actions: [edit, issue, source]
  #downloads: [pdf, epub, docx]

  # https://quarto.org/docs/websites/website-tools.html#google-analytics
  #google-analytics: "G-..."

  #sharing: [twitter, facebook]
  # https://quarto.org/docs/websites/website-tools.html#open-graph
  open-graph: true

  # https://quarto.org/docs/reference/projects/books.html#search
  search: true
    #location: sidebar # navbar, sidebar
    #type: textbox # overlay, textbox

  #cover-image: images/cover.png
  #favicon: images/favicon.ico

  # https://quarto.org/docs/websites/website-navigation.html#side-navigation
  #sidebar:
  #  logo: images/ospo-logo.png

  #sidebar:
  #  contents:
  #    - index.qmd
  #
  #    - section:
  #      href: prereqs/local-dev-setup/index.qmd
  #      title: "Prerequisites"
  #      contents:
  #        - prereqs/local-dev-setup/github.qmd
  #        - prereqs/local-dev-setup/vs-code-text-editor.qmd
  #        - prereqs/local-dev-setup/terminal.qmd
  #        - prereqs/local-dev-setup/anaconda.qmd
  #        - prereqs/local-dev-setup/git-client.qmd


  chapters:
    - index.qmd

    #- "-------------"

    #- part: "Prerequisites"
    #  #href: prereqs/index.qmd
    #  chapters:
    #    - prereqs/dev-tools/code-climate.qmd

    - "-------------"

    - part: "Notes"
      chapters:

        - href: notes/style-guidelines.qmd
          text: "Code Readability and Style"

        - href: notes/documentation.qmd
          text: "Code Documentation"

        - href: notes/complexity.qmd
          text: "Code Complexity"

        - href: notes/refactoring.qmd
          text: "Refactoring"


        - href: notes/modules-imports.qmd
          text: "Code Modularity"

        - href: notes/automated-testing.qmd
          text: "Automated Testing"

        - href: notes/continuous-integration.qmd
          text: "Continuous Integration"


    - "-------------"
    - part: "Exercises"
      chapters:
        - href: exercises/testing-123/exercise.qmd
          text: "Testing 1,2,3"

        - href: exercises/codebase-cleanup/exercise.qmd
          text: "Codebase Cleanup (RPS)"

        #- href: exercises/object-oriented-programming/exercise.qmd
        #  text: Game Loop Class (RPS)

        - href: exercises/notebook-translation/exercise.qmd
          text: "Notebook Translation"




    - "-------------"

  appendices:

    - href: notes/object-oriented-programming.qmd
      text: "Object-oriented Programming"

    - href: notes/custom-classes.qmd
      text: "Custom Classes"

    - href: notes/class-inheritance.qmd
      text: "Class Inheritance"

    - href: notes/code-climate.qmd
      text: "Code Climate"

    - href: notes/pytest.qmd
      text: "The `pytest` Package"

    - href: notes/github-actions.qmd
      text: "GitHub Actions"



  # shows up at bottom of page
  #body-footer: "&copy; Copyright 2024, Your Name Here"

  #page-footer:
  #  center: |
  #    <p>&copy; Copyright 2024, GWU Open Source Program Office (OSPO)</p>


resources:
  - notes/github-actions/*.yml
  #- notes/github-actions/python-app-default.yml
  #- notes/github-actions/python-app-with-database.yml
  #- notes/github-actions/python-app-with-google-creds.yml
  #- notes/github-actions/python-app-with-secrets.yml


#bibliography: references.bib


format:
  html:
    # https://quarto.org/docs/output-formats/html-themes.html
    theme:
      light: default #flatly
      dark: darkly
    css: styles.css
    number-sections: false
    toc-expand: true
    from: markdown+emoji # enable emojis


  #pdf:
  #  documentclass: scrreprt
